// This file was generated by Prisma, but we explicitly load `.env.local`
// so Next.js and Prisma share the same configuration.
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // SQLite local dev fallback (makes the prototype fully functional without Supabase credentials)
    url: (process.env["DATABASE_URL"] ?? "").trim().length > 0
      ? process.env["DATABASE_URL"]
      : "file:./dev.db",
  },
});
